== export-dpi

[role="table table-striped", frame=topbot, grid=rows, cols="2,8"]
|===

|description
|set DPI for bitmap conversion or for rasterization of filters

|supported by
|`s2v-is`

|usage
|`--export-dpi DPI`

|DPI
|the DPI value

|required
|none for the CLI option, 96 in Inkscape

|default value
|none

|dependencies
|`target`

|interactions
|none

|in layers
|yes

|===


=== Description
This option sets the resolution for a bitmap export, here for the target `png`.
It can also be used for fallback rasterization of filtered objects when exporting to `ps`, `eps`, or `pdf`.
There is no default value of the CLI option.
However, Inkscape uses a DPI of 96 as default, which corresponds to 1 SVG user unit (px, also called "user unit") exporting to 1 bitmap pixel.


=== Dependency on other CLI options
This option only has an effect when the target is set to `png`, `ps`, `eps`, or `pdf`.


=== Interaction with other CLI options
None


=== Supported in Layers
Yes

