
<dependency>
	<groupId>batik</groupId>
	<artifactId>batik-bridge</artifactId>
	<version>1.6-1</version>
</dependency>

<dependency>
	<groupId>org.freehep</groupId>
	<artifactId>freehep-graphicsio</artifactId>
	<version>2.4</version>
</dependency>
<dependency>
	<groupId>org.freehep</groupId>
	<artifactId>freehep-graphics2d</artifactId>
	<version>2.4</version>
</dependency>
<dependency>
	<groupId>org.freehep</groupId>
	<artifactId>freehep-graphicsio-emf</artifactId>
	<version>2.4</version>
</dependency>
<dependency>
	<groupId>org.freehep</groupId>
	<artifactId>freehep-graphicsio-pdf</artifactId>
	<version>2.4</version>
</dependency>
<dependency>
	<groupId>org.freehep</groupId>
	<artifactId>freehep-graphicsio-svg</artifactId>
	<version>2.4</version>
</dependency>
