<dependency>
	<groupId>batik</groupId>
	<artifactId>batik-bridge</artifactId>
	<version>1.6</version>
</dependency>
<dependency>
	<groupId>org.freehep</groupId>
	<artifactId>freehep-graphicsio</artifactId>
	<version>2.4</version>
</dependency>
<dependency>
	<groupId>org.freehep</groupId>
	<artifactId>freehep-graphics2d</artifactId>
	<version>2.4</version>
</dependency>
<dependency>
	<groupId>org.freehep</groupId>
	<artifactId>freehep-graphicsio-emf</artifactId>
	<version>2.4</version>
</dependency>
<dependency>
	<groupId>org.freehep</groupId>
	<artifactId>freehep-graphicsio-pdf</artifactId>
	<version>2.4</version>
</dependency>
<dependency>
	<groupId>org.freehep</groupId>
	<artifactId>freehep-graphicsio-svg</artifactId>
	<version>2.4</version>
</dependency>
<dependency>
	<groupId>batik</groupId>
	<artifactId>batik-gvt</artifactId>
	<version>1.6</version>
</dependency>
<dependency>
	<groupId>batik</groupId>
	<artifactId>batik-util</artifactId>
	<version>1.6</version>
</dependency>
<dependency>
	<groupId>batik</groupId>
	<artifactId>batik-dom</artifactId>
	<version>1.6</version>
	<scope>runtime</scope>
</dependency>
<dependency>
	<groupId>batik</groupId>
	<artifactId>batik-svg-dom</artifactId>
	<version>1.6</version>
	<scope>runtime</scope>
</dependency>
<dependency>
	<groupId>batik</groupId>
	<artifactId>batik-css</artifactId>
	<version>1.6</version>
</dependency>
<dependency>
	<groupId>batik</groupId>
	<artifactId>batik-script</artifactId>
	<version>1.6</version>
	<scope>runtime</scope>
</dependency>
<dependency>
	<groupId>batik</groupId>
	<artifactId>batik-ext</artifactId>
	<version>1.6</version>
	<scope>runtime</scope>
</dependency>
<dependency>
	<groupId>batik</groupId>
	<artifactId>batik-awt-util</artifactId>
	<version>1.6</version>
	<scope>runtime</scope>
</dependency>
<dependency>
	<groupId>batik</groupId>
	<artifactId>batik-parser</artifactId>
	<version>1.6</version>
	<scope>runtime</scope>
</dependency>
<dependency>
	<groupId>batik</groupId>
	<artifactId>batik-xml</artifactId>
	<version>1.6</version>
	<scope>runtime</scope>
</dependency>
<dependency>
	<groupId>org.axsl.org.w3c.dom.svg</groupId>
	<artifactId>svg-dom-java</artifactId>
	<version>1.1</version>
	<scope>runtime</scope>
</dependency>
<dependency>
	<groupId>xerces</groupId>
	<artifactId>xerces</artifactId>
	<version>2.4.0</version>
	<scope>runtime</scope>
</dependency>