SVG 2 Vector
------------

SVG to vector converter.

This tool converts an SVG graphic to a vector format. Currently supported targets are EMF, PDF and SVG. The tool does support SVG and SVGZ input formats.
It also can deal with SVG layers. Input can be a file or a URL. Output can be a single file or a set of files, i.e. handling SVG layers individually.
This means that the tool can be part of a tool chain for creating animations. Simply create an SVG image with several layers, one per step of an animation.
Then use this tool to create an image per layer and use them in the target publication platform: 

* EMF - for animations in any Microsoft Office product, e.g. PowerPoint
* PDF - for animations in the LaTeX package beamer
* SVG - for animations using HTML pages and SVG images

All images are created using a custom page size (PDF, SVG) or a custome image size (EMF).
This means that the created image has the size of the original image, even for PDFs.
Margins are set to 0, so there are no extras around the converted image either.

Input options (one is required): 

* +-f,--file arg+ = input file, SVG or SVGZ coded, Inkscape formats are supported
* +-u,--uri arg+ = input URL, points to a file, SVG or SVGZ coded, Inkscape formats are supported

Output options:

* +-t,--target arg+ = target vector format, supported are: emf, pdf, svg
* +-o,--output arg+ = output file if no special layer processing is activated, default is the base name of the input file
* +-d,--directory arg+ = output directory, default is the current directory

Process Options:

* +-v,--verbose+ = verbose mode, prints process of the conversion
* +-h,--help+ = prints a help screen with all command line options

Render Options:

* +-b,--no-background+ = switch off background
* +-c,--clip+ = activate clipping
* +-n,--not-transparent+ = switch of transpararency
* +-r,--bgrnd-color arg+ = sets the background color
* +-s,--not-text-as-shape+ = switch of text-as-shape property

Layer Options:

* +-l,--one-per-layer+ = activates special process for layers creating one output file per layer
* +-i,--use-layer-index+ = use layer index for SVG layer processing, default is layer ID
* +-I,--use-layer-index-id+ = use layer index and ID for SVG layer processing, default is layer ID
